# Generated by Django 4.2 on 2023-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_app', '0002_categorie_course_lesson_notice_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='categoryId',
        ),
    ]
