# Generated by Django 4.2 on 2023-04-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_app', '0006_alter_answernotice_options_alter_notice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='answernotice',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
